--CREATE TABLE employee (
--	id INT NOT NULL,
--	name VARCHAR(50) NOT NULL,
--	birthday DATE NOT NULL,
--	email VARCHAR(100) NOT NULL
--);

------------------------------------------------------------------------------------------------------------------------------

--insert into employee (id, name, email, birthday) values (1, 'Euell Rudge', 'erudge0@jalbum.net', '1967-03-15 07:17:56');
--insert into employee (id, name, email, birthday) values (2, 'Rosemary Clissell', 'rclissell1@mozilla.org', '1979-07-16 22:41:20');
--insert into employee (id, name, email, birthday) values (3, 'Katti Bertelsen', 'kbertelsen2@purevolume.com', '1907-02-04 18:33:44');
--insert into employee (id, name, email, birthday) values (4, 'Felisha Formigli', 'fformigli3@china.com.cn', '1968-11-28 14:44:46');
--insert into employee (id, name, email, birthday) values (5, 'Thatcher Schlag', 'tschlag4@jiathis.com', '1968-12-22 23:44:12');
--insert into employee (id, name, email, birthday) values (6, 'Elyn Bourdice', 'ebourdice5@earthlink.net', '1901-08-25 01:10:08');
--insert into employee (id, name, email, birthday) values (7, 'Trina Kevis', 'tkevis6@usda.gov', '1949-03-03 16:52:04');
--insert into employee (id, name, email, birthday) values (8, 'Fleurette Dunsford', 'fdunsford7@google.ca', '1937-05-07 09:09:01');
--insert into employee (id, name, email, birthday) values (9, 'Emmie Mapplebeck', 'emapplebeck8@google.com.br', '1977-12-07 03:56:51');
--insert into employee (id, name, email, birthday) values (10, 'Keelia Vink', 'kvink9@usatoday.com', '1987-09-06 04:55:27');
--insert into employee (id, name, email, birthday) values (11, 'Trenton Bonwell', 'tbonwella@marriott.com', '1906-07-25 09:45:00');
--insert into employee (id, name, email, birthday) values (12, 'Mandy Ipplett', 'mipplettb@marriott.com', '2010-11-14 14:08:11');
--insert into employee (id, name, email, birthday) values (13, 'Josephina Test', 'jtestc@ehow.com', '1960-10-17 21:48:33');
--insert into employee (id, name, email, birthday) values (14, 'Wildon Aylen', 'waylend@google.co.uk', '1922-08-30 17:29:41');
--insert into employee (id, name, email, birthday) values (15, 'Nanni Lounds', 'nloundse@cafepress.com', '2007-09-04 13:38:21');
--insert into employee (id, name, email, birthday) values (16, 'Steven Mattiazzi', 'smattiazzif@cam.ac.uk', '1905-08-12 07:02:11');
--insert into employee (id, name, email, birthday) values (17, 'Velma Dillway', 'vdillwayg@rakuten.co.jp', '1909-03-09 04:02:15');
--insert into employee (id, name, email, birthday) values (18, 'Gloriane Bowering', 'gboweringh@cam.ac.uk', '1917-03-20 09:14:33');
--insert into employee (id, name, email, birthday) values (19, 'Christel Waddilove', 'cwaddilovei@delicious.com', '1950-04-03 16:58:22');
--insert into employee (id, name, email, birthday) values (20, 'Doralia Ludron', 'dludronj@livejournal.com', '1949-11-17 03:28:14');
--insert into employee (id, name, email, birthday) values (21, 'Maribelle Sellek', 'msellekk@blog.com', '1937-01-22 17:01:32');
--insert into employee (id, name, email, birthday) values (22, 'Rube Consterdine', 'rconsterdinel@disqus.com', '1954-02-19 15:57:52');
--insert into employee (id, name, email, birthday) values (23, 'Robbyn Lowdwell', 'rlowdwellm@amazon.com', '1917-04-28 07:44:13');
--insert into employee (id, name, email, birthday) values (24, 'Stacia Boutellier', 'sboutelliern@uol.com.br', '1929-06-03 03:56:02');
--insert into employee (id, name, email, birthday) values (25, 'Pernell Lillyman', 'plillymano@hp.com', '1960-09-16 18:46:33');
--insert into employee (id, name, email, birthday) values (26, 'Clotilda De Angelo', 'cdep@mtv.com', '2013-08-15 10:36:57');
--insert into employee (id, name, email, birthday) values (27, 'Oralie Yanukhin', 'oyanukhinq@tripadvisor.com', '1965-06-01 22:46:36');
--insert into employee (id, name, email, birthday) values (28, 'Mark Cheak', 'mcheakr@abc.net.au', '1997-02-20 02:08:06');
--insert into employee (id, name, email, birthday) values (29, 'Paulita Price', 'pprices@livejournal.com', '1916-04-22 04:19:53');
--insert into employee (id, name, email, birthday) values (30, 'Melly Ransfield', 'mransfieldt@godaddy.com', '1915-01-09 21:29:05');
--insert into employee (id, name, email, birthday) values (31, 'Clerkclaude Betancourt', 'cbetancourtu@studiopress.com', '1990-08-28 16:42:34');
--insert into employee (id, name, email, birthday) values (32, 'Shayla Droghan', 'sdroghanv@ucoz.com', '1964-09-20 20:58:20');
--insert into employee (id, name, email, birthday) values (33, 'Lauren Peter', 'lpeterw@walmart.com', '1991-10-15 16:37:39');
--insert into employee (id, name, email, birthday) values (34, 'Calhoun Burleton', 'cburletonx@comcast.net', '1947-09-05 13:14:59');
--insert into employee (id, name, email, birthday) values (35, 'Rene Moxley', 'rmoxleyy@businesswire.com', '1967-07-26 06:12:34');
--insert into employee (id, name, email, birthday) values (36, 'Veronique Nottingam', 'vnottingamz@taobao.com', '1916-01-26 15:54:35');
--insert into employee (id, name, email, birthday) values (37, 'Judas Fenne', 'jfenne10@cam.ac.uk', '1921-04-05 12:00:18');
--insert into employee (id, name, email, birthday) values (38, 'Field Yellowlee', 'fyellowlee11@reverbnation.com', '1961-02-24 10:20:33');
--insert into employee (id, name, email, birthday) values (39, 'Torey Crocroft', 'tcrocroft12@blog.com', '1947-11-21 12:48:09');
--insert into employee (id, name, email, birthday) values (40, 'Thelma Mattiuzzi', 'tmattiuzzi13@bizjournals.com', '1901-10-26 02:24:55');
--insert into employee (id, name, email, birthday) values (41, 'Selig Celand', 'sceland14@uiuc.edu', '1918-04-05 21:43:23');
--insert into employee (id, name, email, birthday) values (42, 'Kathi Breslin', 'kbreslin15@va.gov', '1977-02-13 20:54:53');
--insert into employee (id, name, email, birthday) values (43, 'Roch Yurenev', 'ryurenev16@meetup.com', '1901-04-20 01:23:29');
--insert into employee (id, name, email, birthday) values (44, 'Marice Peasegod', 'mpeasegod17@tinypic.com', '1934-08-01 23:20:26');
--insert into employee (id, name, email, birthday) values (45, 'Giles Paulat', 'gpaulat18@guardian.co.uk', '1934-04-08 17:02:04');
--insert into employee (id, name, email, birthday) values (46, 'Jasmine Oldmeadow', 'joldmeadow19@hud.gov', '2019-11-11 20:56:20');
--insert into employee (id, name, email, birthday) values (47, 'Ceciley Brimblecombe', 'cbrimblecombe1a@naver.com', '2010-02-26 09:39:12');
--insert into employee (id, name, email, birthday) values (48, 'Yorgos Lunam', 'ylunam1b@cafepress.com', '1963-03-20 19:07:55');
--insert into employee (id, name, email, birthday) values (49, 'Jephthah Rabat', 'jrabat1c@vinaora.com', '1935-09-07 20:32:22');
--insert into employee (id, name, email, birthday) values (50, 'Flore Stangroom', 'fstangroom1d@123-reg.co.uk', '1916-02-15 11:53:58');

-----------------------------------------------------------------------------------------------------------------------------------------------

--UPDATE employee
--SET email = 'null@null.null'
--WHERE id > 45;

---------------------------------------------------------------------------------------------------------------------------------

--DELETE FROM employee
--WHERE email = 'null@null.null'


