(SELECT FIRST_NAME FROM ACTOR)
UNION
(SELECT FIRST_NAME FROM CUSTOMER)

-----------------------------------------

(SELECT FIRST_NAME FROM ACTOR)
INTERSECT
(SELECT FIRST_NAME FROM CUSTOMER)

-----------------------------------------

(SELECT FIRST_NAME FROM ACTOR)
EXCEPT
(SELECT FIRST_NAME FROM CUSTOMER)

-----------------------------------------

(SELECT FIRST_NAME FROM ACTOR)
UNION ALL
(SELECT FIRST_NAME FROM CUSTOMER)

(SELECT FIRST_NAME FROM ACTOR)
EXCEPT ALL
(SELECT FIRST_NAME FROM CUSTOMER)







